#email: hi@ratan.me
#title: blog.ratan.me
#baseurl: "http://blog.ratan.me" # the subpath of your site, e.g. /blog
url: "http://blog.ratan.me" # the base hostname & protocol for your site
#twitter_username: imratan19
#github_username:  jekyll
#excerpt_separator: <!--more--> 
nav-search: search

# Build settings
markdown: kramdown
permalink: /:title
#theme: minima

gems: [jekyll-paginate]
gems: [jekyll-paginate, jekyll-coffeescript, jekyll-watch, jekyll-assets]
gems: [jekyll-seo-tag]
paginate: 5
#paginate_path: "/blog/"
paginate_path: "/blog/page:num/"
sass:
  sass_dir: _sass
  style: compressed
